package com.ainosoft.demo.pojo;

// Generated 13 Feb, 2015 11:07:05 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Addressbook generated by hbm2java
 */
@Entity
@Table(name = "Addressbook", catalog = "viewdb")
public class Addressbook implements java.io.Serializable {

	private Integer bookId;
	private String bookName;

	public Addressbook() {
	}

	public Addressbook(String bookName) {
		this.bookName = bookName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "book_id", unique = true, nullable = false)
	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	@Column(name = "book_name", length = 45)
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Override
	public boolean equals(Object obj) {
		if ( obj instanceof Addressbook){
			Addressbook ab = (Addressbook) obj ;
			if (ab.getBookId() == this.getBookId())
				return true ;
		}
		return false ;
	}
}
