package com.ainosoft.demo.pojo;

// Generated 13 Feb, 2015 11:07:05 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "Address", catalog = "viewdb")
public class Address implements java.io.Serializable {

	private int addressId;
	private String state;
	private String country;
	private String city;

	public Address() {
	}

	public Address(int addressId) {
		this.addressId = addressId;
	}

	public Address(int addressId, String state, String country, String city) {
		this.addressId = addressId;
		this.state = state;
		this.country = country;
		this.city = city;
	}

	@Id
	@Column(name = "address_id", unique = true, nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	@Override
	public boolean equals(Object obj) {
		if ( obj instanceof Address){
			Address group = (Address) obj ;
			if (group.getAddressId() == this.getAddressId())
				return true ;
		}
		return false ;
	}
}
