package com.ainosoft.demo.pojo;

// Generated 13 Feb, 2015 11:07:05 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NewView generated by hbm2java
 */
@Entity
@Table(name = "new_view", catalog = "viewdb")
public class NewView implements java.io.Serializable {

	private NewViewId id;

	public NewView() {
	}

	public NewView(NewViewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bookId", column = @Column(name = "book_id", nullable = false)),
			@AttributeOverride(name = "bookName", column = @Column(name = "book_name", length = 45)),
			@AttributeOverride(name = "addressId", column = @Column(name = "address_id", nullable = false)),
			@AttributeOverride(name = "state", column = @Column(name = "state", length = 45)),
			@AttributeOverride(name = "country", column = @Column(name = "country", length = 45)),
			@AttributeOverride(name = "city", column = @Column(name = "city", length = 45)) })
	public NewViewId getId() {
		return this.id;
	}

	public void setId(NewViewId id) {
		this.id = id;
	}

}
