package com.ainosoft.demo.pojo;

// Generated 13 Feb, 2015 11:07:05 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NewViewId generated by hbm2java
 */
@Embeddable
public class NewViewId implements java.io.Serializable {

	private int bookId;
	private String bookName;
	private int addressId;
	private String state;
	private String country;
	private String city;

	public NewViewId() {
	}

	public NewViewId(int bookId, int addressId) {
		this.bookId = bookId;
		this.addressId = addressId;
	}

	public NewViewId(int bookId, String bookName, int addressId, String state,
			String country, String city) {
		this.bookId = bookId;
		this.bookName = bookName;
		this.addressId = addressId;
		this.state = state;
		this.country = country;
		this.city = city;
	}

	@Column(name = "book_id", nullable = false)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	@Column(name = "book_name", length = 45)
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Column(name = "address_id", nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NewViewId))
			return false;
		NewViewId castOther = (NewViewId) other;

		return (this.getBookId() == castOther.getBookId())
				&& ((this.getBookName() == castOther.getBookName()) || (this
						.getBookName() != null
						&& castOther.getBookName() != null && this
						.getBookName().equals(castOther.getBookName())))
				&& (this.getAddressId() == castOther.getAddressId())
				&& ((this.getState() == castOther.getState()) || (this
						.getState() != null && castOther.getState() != null && this
						.getState().equals(castOther.getState())))
				&& ((this.getCountry() == castOther.getCountry()) || (this
						.getCountry() != null && castOther.getCountry() != null && this
						.getCountry().equals(castOther.getCountry())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null
						&& castOther.getCity() != null && this.getCity()
						.equals(castOther.getCity())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookId();
		result = 37 * result
				+ (getBookName() == null ? 0 : this.getBookName().hashCode());
		result = 37 * result + this.getAddressId();
		result = 37 * result
				+ (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result
				+ (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result
				+ (getCity() == null ? 0 : this.getCity().hashCode());
		return result;
	}

}
